import Head from 'next/head'
import Image from 'next/image'
import client from '../utils/sanityAPI'
import { GetStaticPropsContext } from 'next/types'
import Nav from '../components/nav'
import LandingCover from '../components/LandingCover'



export default function Home({ name }: { name: string }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <LandingCover />
      </main>
    </>
  )
}

// export async function getStaticProps(context: GetStaticPropsContext) {
//   const query = '*[_type == "blog"]'
//   let name;
//   await client.fetch(query).then((bikes: any) => {
//     name = bikes[0].name
//   })

//   console.log(name, 'check me');
//   return {
//     props: { name }, // will be passed to the page component as props
//   }
// }