import Head from 'next/head'
import Image from 'next/image'
import client from '../utils/sanityAPI'
import { GetStaticPropsContext } from 'next/types'
import Nav from '../components/nav'
import LandingCover from '../components/LandingCover'

import GeneralTextBlock from '../components/Blocks/GeneralTextBlock'
import HookBlock from '../components/Blocks/HookBlock'
import ImageBlock from '../components/Blocks/ImageBlock'
import FooterLayout from '../components/LayoutComponents/Footer'


export default function Home({ name }: { name: string }) {
  return (
    <>
      <Head>
        <title>NakamaFC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <LandingCover />
        <HookBlock />
        <ImageBlock />
        <GeneralTextBlock />
        <ImageBlock />
        <HookBlock />
        <FooterLayout primaryBlock={'component here'} secondaryBlock={'maybe a smaller one here'} />
      </main>
    </>
  )
}

// export async function getStaticProps(context: GetStaticPropsContext) {
//   const query = '*[_type == "blog"]'
//   let name;
//   await client.fetch(query).then((bikes: any) => {
//     name = bikes[0].name
//   })

//   console.log(name, 'check me');
//   return {
//     props: { name }, // will be passed to the page component as props
//   }
// }